# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(800, 600)
        self.gridLayoutWidget = QtWidgets.QWidget(Widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 30, 751, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gridLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.column_header = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.column_header.setObjectName("column_header")
        self.verticalLayout_3.addWidget(self.column_header)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.content = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.content.setObjectName("content")
        self.verticalLayout_4.addWidget(self.content)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 7)
        self.submit = QtWidgets.QPushButton(Widget)
        self.submit.setGeometry(QtCore.QRect(690, 400, 93, 28))
        self.submit.setObjectName("submit")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Widget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 440, 751, 131))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.result = QtWidgets.QTextBrowser(self.gridLayoutWidget_2)
        self.result.setObjectName("result")
        self.gridLayout_3.addWidget(self.result, 0, 1, 1, 1)
        self.add = QtWidgets.QPushButton(Widget)
        self.add.setGeometry(QtCore.QRect(690, 190, 93, 28))
        self.add.setObjectName("add")
        self.input_display = QtWidgets.QTextBrowser(Widget)
        self.input_display.setGeometry(QtCore.QRect(30, 240, 751, 141))
        self.input_display.setObjectName("input_display")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.label.setText(_translate("Widget", "column_header"))
        self.label_2.setText(_translate("Widget", "content"))
        self.submit.setText(_translate("Widget", "submit"))
        self.label_3.setText(_translate("Widget", "result"))
        self.add.setText(_translate("Widget", "add"))
